### ISSUE TITLE
Remove react plugin

### ISSUE THREAD

**Issue by kralion** [kralion/blue-motors#12]
Work using just astro, because the pages are static, so there is no need to use reactjs in this project.

**Comment by MiguelRequenaR** [comment]
For use the library for navbar, needed ReactJS. 
![monodurmiendoFINAL](https://github.com/user-attachments/assets/6c2963db-82b0-4631-a782-33ae9f7ba0a8)

**Comment by Yuriine** [comment]
It is required to use the libraries as frramer

**Comment by kralion** [comment]
I've thoroughly reviewed the issue and concluded that using React is the needed. However, to avoid bugs and warnings, it's crucial to use `className` instead of `class` in those components. This is particularly important as I've noticed several incompatibilities in the development tools, which can be resolved by following this convention.
